---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.13/website/content/v1.13/schemas/config.schema.json
machine:
  install:
    disk: /dev/nvme0n1
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: rk1
---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
links:
  - end0
bondMode: active-backup
miimon: 100
mtu: 1500
addresses:
  - address: 192.168.20.34/24
  - address: fdd5:aa8:9535:20::34/64
routes:
  - gateway: 192.168.20.1
  - gateway: fdd5:aa8:9535:20::1
