---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app whoami
spec:
  chartRef:
    kind: OCIRepository
    name: whoami
  interval: 1h
  values:
    controllers:
      whoami:
        replicas: 2
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: mirror.gcr.io/traefik/whoami
              tag: v1.11.0
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 16Mi
              limits:
                memory: 32Mi
    defaultPodOptions:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
    service:
      app:
        ipFamilyPolicy: PreferDualStack
        ports:
          http:
            port: 80
    route:
      main:
        parentRefs:
          - name: envoy-external
            namespace: network
        hostnames:
          - whoami.${CLUSTER_DOMAIN}
