---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky-ui
spec:
  chartRef:
    kind: OCIRepository
    name: blocky-ui
  interval: 1h
  values:
    controllers:
      castor:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/gabeduartem/blocky-ui
              tag: 1.7.0@sha256:51b3fdc5c3d4d184e0a06126e1761df6b4ca948b9788ab3944dda3c07da287b5
            env:
              # QUERY_LOG_TYPE: postgresql
              # QUERY_LOG_TARGET:
              #   secretKeyRef:
              #     name: blocky-db-app
              #     key: uri
              BLOCKY_API_URL: http://blocky1.${PRIVATE_STATIC_DOMAIN}:4000
            probes:
              liveness:
                enabled: true
                type: HTTP
              readiness:
                enabled: true
                type: HTTP
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 512Mi
      pollux:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/gabeduartem/blocky-ui
              tag: 1.7.0@sha256:51b3fdc5c3d4d184e0a06126e1761df6b4ca948b9788ab3944dda3c07da287b5
            env:
              # QUERY_LOG_TYPE: postgresql
              # QUERY_LOG_TARGET:
              #   secretKeyRef:
              #     name: blocky-db-app
              #     key: uri
              BLOCKY_API_URL: http://blocky2.${PRIVATE_STATIC_DOMAIN}:4000
            probes:
              liveness:
                enabled: true
                type: HTTP
              readiness:
                enabled: true
                type: HTTP
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile: {type: RuntimeDefault}
    service:
      castor:
        controller: castor
        ports:
          http:
            port: &port 3000
      pollux:
        controller: pollux
        ports:
          http:
            port: *port
    route:
      castor:
        hostnames:
          - blocky1.${CLUSTER_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: castor
                port: *port
      pollux:
        hostnames:
          - blocky2.${CLUSTER_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: pollux
                port: *port
