---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: garage-secret
    template:
      data:
        GARAGE_ADMIN_TOKEN: "{{ .garage_admin_token }}"
  dataFrom:
    - extract:
        key: garage
      rewrite:
        - regexp:
            source: "(.*)"
            target: "garage_$1"
