apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:KA1pxPzgIvUj+7j7,iv:wJZJMiDXnmJWb70GSMG+PbJkNy3dXh3dmUE5K3JgINU=,tag:lSleR60ul0M9u2O98MdoDA==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:fw2j9CxwtCB5cHnZf1kS9rybPff7gIkC2qVNUqASwvfmMkof,iv:IxQ99UJJN5nMI3TRwoK9nER7U9GUL5qiQ+8AIOpz80k=,tag:J3dC/KcZrRoLhcWS9LKv7Q==,type:str]
  PRIVATE_STATIC_DOMAIN: ENC[AES256_GCM,data:uOLV7iTmKqWer74j,iv:KgHIRjk3Aa/cK1tr/3GdchPGXxgXXU2jx4oQ4WgyYh4=,tag:ntzbQZmKHGRqmXUrmLsiHQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQWVvTkVtbEpnN1NVaXdK
        SXl0MFJEeHVnZmtVQ1UxelEzWDBsK09yU2pVCm95VTdPaGZhN0hxNFBTTU9CbTIx
        Y0RsSUdFY1pYeURvZ2EzSjUwejQ4NXMKLS0tIG9GZldhV1JWcTJ5QVRTV3N5QWFs
        UmRGUUhqZ2ZyeDJlbUZ6b3E5Tkdqd2cKNqkTG3jCbbgQE4+fCC5F73WrC8SfpH8x
        cvAlvFFxDnQulSPtXLKiuKxVS9iYfiQtHtaIdCfm7rXJlNnvTOlbGQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-17T20:11:34Z"
  mac: ENC[AES256_GCM,data:8qjG5T1Sh2toA9f7IJtFmt6y8Sy7DevsdexlcptaJXcAgRtjl4gPHxiineqmEzHyZ4FLRAw4UqmkwKdKRqaBJh5ig28uSejmevwkyfYpK7QDhh5S3zgB8BtA991eyZCIZZWfZh1kEOq66gpDVfuF9LSOZB8c84AbfsAP1TKOp5g=,iv:pwnter6sr2ALVzk4bnm8ivtHU1u3uXreEjOk6/iezns=,tag:PBCUyjbXaOM3vg0XgfFmDQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
