---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ocis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ocis-secret
    template:
      data:
        OCIS_JWT_SECRET: "{{ .OCIS_JWT_SECRET }}"
        OCIS_SERVICE_ACCOUNT_ID: "{{ .service_account_id }}"
        OCIS_SERVICE_ACCOUNT_SECRET: "{{ .service_account_secret }}"
        OCIS_LDAP_BIND_PASSWORD: "{{ .ldap_bind_password }}"
  dataFrom:
    - extract:
        key: ocis
    - extract:
        key: opencloud
