---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tplink-plug-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: tplink-plug-exporter
  interval: 1h
  values:
    controllers:
      tplink-plug-exporter:
        containers:
          app:
            image:
              repository: ghcr.io/haraldkoch/tplink-plug-exporter
              tag: 0.5.2@sha256:defa0b2162d10fdc2f59751aba16bd554af9c51e1ae6eb94e169f911194679d6
            env:
              TZ: ${TIMEZONE:=Etc/UTC}
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 100Mi
    service:
      app:
        ports:
          metrics:
            protocol: TCP
            port: 9233
