---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tekton-results-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tekton-results-postgres
    template:
      data:
        DB_USER: "{{ .tekton_postgres_user }}"
        DB_PASSWORD: "{{ .tekton_postgres_pass }}"
        POSTGRES_USER: "{{ .tekton_postgres_user }}"
        POSTGRES_PASSWORD: "{{ .tekton_postgres_pass }}"
        #
        INIT_POSTGRES_DBNAME: tekton-results
        INIT_POSTGRES_HOST: postgres-rw.dbms.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .tekton_postgres_user }}"
        INIT_POSTGRES_PASS: "{{ .tekton_postgres_pass }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: tekton
      rewrite:
        - regexp:
            source: "(.*)"
            target: "tekton_$1"
    - extract:
        key: cloudnative-pg
