---
# Note: Gatus vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
alerting:
  pushover:
    title: Gatus (Kubernetes)
    application-token: $${PUSHOVER_TOKEN}
    user-key: $${PUSHOVER_USER_KEY}
    priority: 1
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover

  - name: Google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover

  - name: Quad9
    group: connectivity
    url: icmp://9.9.9.9
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover

  - name: status
    group: guarded
    url: 1.1.1.1
    interval: 1m
    dns:
      query-name: "status.${CLUSTER_DOMAIN}"
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: pushover

  - name: flux-webhook
    group: guarded
    url: 1.1.1.1
    interval: 1m
    dns:
      query-name: flux-webhook.${CLUSTER_DOMAIN}
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: pushover

  - name: DNS Primary (castor)
    group: internal
    url: "192.168.10.6"
    interval: 1m
    dns:
      query-name: "www.${CLUSTER_DOMAIN}"
      query-type: "A"
    conditions:
      - "[BODY] == 192.168.21.80"
      - "[DNS_RCODE] == NOERROR"
    alerts:
      - type: pushover

  - name: DNS Secondary (pollux)
    group: internal
    url: "192.168.10.7"
    interval: 1m
    dns:
      query-name: "www.${CLUSTER_DOMAIN}"
      query-type: "A"
    conditions:
      - "[BODY] == 192.168.21.80"
      - "[DNS_RCODE] == NOERROR"
    alerts:
      - type: pushover

  - name: DNS Router
    group: internal
    url: "192.168.20.1"
    interval: 1m
    dns:
      query-name: "www.${CLUSTER_DOMAIN}"
      query-type: "A"
    conditions:
      - "[BODY] == 172.64.80.1"
      - "[DNS_RCODE] == NOERROR"
    alerts:
      - type: pushover

metrics: true

storage:
  type: postgres
  path: postgres://$${INIT_POSTGRES_USER}:$${INIT_POSTGRES_PASS}@$${INIT_POSTGRES_HOST}:5432/$${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/7131938
  link: https://github.com/haraldkoch
  buttons:
    - name: Github
      link: https://github.com/haraldkoch
    - name: Homelab
      link: https://github.com/haraldkoch/kochhaus-home

web:
  port: $${GATUS_WEB_PORT}
