---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-backup
spec:
  interval: 1h
  path: ./kubernetes/apps/base/dbms/postgres-backup
  postBuild:
    substitute:
      DATABASES: authelia,dmarc,docmost,gatus,lldap,nextcloud,speedtest,tekton-results
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
