---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: harbor-secret
    template:
      data:
        harbor_postgres_password: "{{ .harbor_postgres_password }}"
        harbor_admin_password: "{{ .harbor_admin_password }}"
        harbor_encryption_key: "{{ .harbor_encryption_key }}"
  dataFrom:
    - extract:
        key: harbor
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9 -]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "harbor_$1"
