---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidctest
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oidctest
    template:
      data:
        OIDC_CLIENT_ID: "{{ .oidc_client_id }}"
        OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
  dataFrom:
    - extract:
        key: oidctest
