---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mealie-secret
    template:
      data:
        OIDC_CLIENT_ID: mealie
        OIDC_CLIENT_SECRET: "{{ .mealie_oidc_client_secret }}"
        POSTGRES_USER: mealie
        POSTGRES_PASSWORD: "{{ .mealie_postgres_pass }}"
        POSTGRES_SERVER: postgres-rw.dbms.svc.cluster.local.
        POSTGRES_PORT: "5432"
        POSTGRES_DB: mealie
        # --
        INIT_POSTGRES_DBNAME: mealie
        INIT_POSTGRES_HOST: postgres-rw.dbms.svc.cluster.local.
        INIT_POSTGRES_PASS: "{{ .mealie_postgres_pass }}"
        INIT_POSTGRES_USER: mealie
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: mealie
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mealie_$1"
    - extract:
        key: cloudnative-pg
