---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  chartRef:
    kind: OCIRepository
    name: mealie
  interval: 1h
  values:
    controllers:
      mealie:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.4.0@sha256:ebd9d30add17acdf935d73eb004758c7dfd9388aaa605fda70ad74378ab92aec
            envFrom:
              - secretRef:
                  name: mealie-secret
        containers:
          mealie:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.20.0@sha256:060031897306aaee2cafd098ebe718f0d649abceac3a3f29801e6dab5f6db04b
            env:
              ALLOW_PASSWORD_LOGIN: "true"
              ALLOW_SIGNUP: "false"
              API_PORT: &port 9000
              BASE_URL: https://mealie.${CLUSTER_DOMAIN}
              DB_ENGINE: postgres
              OIDC_ADMIN_GROUP: mealie_admins
              OIDC_AUTH_ENABLED: "true"
              OIDC_CONFIGURATION_URL: https://auth.${CLUSTER_DOMAIN}/.well-known/openid-configuration
              OIDC_PROVIDER_NAME: Authelia
              OIDC_REMEMBER_ME: "true"
              OIDC_SIGNUP_ENABLED: "true"
              # OPENAI_MODEL: gpt-5-mini
              SMTP_HOST: smtp.${CLUSTER_DOMAIN}
              SMTP_PORT: "25"
              SMTP_FROM_EMAIL: mealie@${CLUSTER_DOMAIN}
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: mealie-secret
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/app/about
                    port: *port
              readiness: *probe
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: true
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 911
        runAsGroup: 911
        fsGroup: 911
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      data:
        existingClaim: ${APP}
        advancedMounts:
          mealie:
            mealie:
              - path: /app/data
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    route:
      mealie:
        hostnames:
          - mealie.${CLUSTER_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: mealie
                port: *port
    service:
      mealie:
        controller: mealie
        ports:
          http:
            port: *port
