---
# Areas
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file: "bootstrap/**/*"
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "README.md"
area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: "kubernetes/**/*"
area/renovate:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/renovate/**/*"
          - ".github/renovate.json5"
area/scripts:
  - changed-files:
      - any-glob-to-any-file: "scripts/**/*"
area/talos:
  - changed-files:
      - any-glob-to-any-file: "talos/**/*"
area/taskfile:
  - changed-files:
      - any-glob-to-any-file:
          - ".taskfiles/**/*"
          - "Taskfile.yaml"
# Clusters
cluster/base:
  - changed-files:
      - any-glob-to-any-file: kubernetes/apps/base/**/*
cluster/main:
  - changed-files:
      - any-glob-to-any-file: kubernetes/apps/main/**/*
      - any-glob-to-any-file: talos/main/**/*
cluster/network:
  - changed-files:
      - any-glob-to-any-file: kubernetes/apps/network/**/*
      - any-glob-to-any-file: talos/network/**/*
cluster/registry:
  - changed-files:
      - any-glob-to-any-file: kubernetes/apps/registry/**/*
      - any-glob-to-any-file: talos/registry/**/*
cluster/test:
  - changed-files:
      - any-glob-to-any-file: kubernetes/apps/test/**/*
      - any-glob-to-any-file: talos/test/**/*
