---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homer
spec:
  chartRef:
    kind: OCIRepository
    name: homer
  interval: 1h
  values:
    controllers:
      homer:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/bastienwirtz/homer
              tag: v26.4.2@sha256:ace7c6a2cfb66e13f0e94d5534cb569562f190aa5cac9446b2453ef7822cd195
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 50Mi
              requests:
                cpu: 10m
                memory: 20Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    defaultPodOptions:
      securityContext:
        fsGroup: 1022
        runAsGroup: 1022
        runAsNonRoot: true
        runAsUser: 1022
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames:
          - "landing.${CLUSTER_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        name: homer
        type: configMap
        globalMounts:
          - path: /www/assets/config.yml
            subPath: config.yml
