---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/common

replacements:
  - path: ../../../components/replacements/ks.yaml

resources:
  - ./namespace.yaml
  - ./media-nfs.yaml
  - ./bookboss.yaml
  - ./calibre-web.yaml
  - ./chaski.yaml
  - ./docmost.yaml
  - ./echo.yaml
  - ./excalidraw.yaml
  - ./filebrowser.yaml
  - ./jellyfin.yaml
  - ./karakeep.yaml
  - ./mealie.yaml
  - ./media-browser.yaml
  - ./nextcloud.yaml
  - ./oidctest.yaml
  - ./onedrive.yaml
  - ./opnsense-backup.yaml
  - ./picoshare.yaml
  - ./populator-test/ks.yaml
  - ./static-web.yaml
  - ./syncthing.yaml
  - ./tautulli.yaml
  - ./trek.yaml
  - ./whoami.yaml
  - ./your-spotify.yaml
