---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # ## Non Cluster resources
        # HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_TAG }}"
        # HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .MAIN_CLOUDFLARE_TUNNEL_ID }}"
        # HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .cloudflare_key }}"
        ## Home
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .hass_token }}"
        ## Infrastructure
        HOMEPAGE_VAR_OMADA_USERNAME: "{{ .omada_username }}"
        HOMEPAGE_VAR_OMADA_PASSWORD: "{{ .omada_password }}"
        ## Media
        # HOMEPAGE_VAR_CALIBRE_USERNAME: "{{ .calibre_username }}"
        # HOMEPAGE_VAR_CALIBRE_PASSWORD: "{{ .calibre_password }}"
        HOMEPAGE_VAR_PLEX_TOKEN: "{{ .plex_token }}"
        HOMEPAGE_VAR_TAUTULLI_TOKEN: "{{ .TAUTULLI_API_KEY }}"
        ## Monitoring
        #HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .grafana_username }}"
        #HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .grafana_password }}"
  data:
    - secretKey: hass_token
      remoteRef:
        key: home-assistant
        property: homepage_apikey
    # Media
    # - secretKey: calibre_username
    #   remoteRef:
    #     key: calibre
    #     property: username
    # - secretKey: calibre_password
    #   remoteRef:
    #     key: calibre
    #     property: password
    - secretKey: plex_token
      remoteRef:
        key: plex
        property: token
        #- secretKey: grafana_username
        #  remoteRef:
        #    key: grafana
        #    property: username
        #- secretKey: grafana_password
        #  remoteRef:
        #    key: grafana
        #    property: password
  dataFrom:
    - extract:
        key: cloudflare-main
      rewrite:
        - regexp:
            source: "(.*)"
            target: "$1_MAIN"
    - extract:
        key: cloudflare-network
      rewrite:
        - regexp:
            source: "(.*)"
            target: "$1_NETWORK"
    - extract:
        key: omada-exporter
      rewrite:
        - regexp:
            source: "(.*)"
            target: "omada_$1"
    - extract:
        key: tautulli
