---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./kochhaus.yaml
configMapGenerator:
  - name: renovate-entrypoint
    files:
      - renovate-entrypoint.sh=./renovate-entrypoint.sh
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  disableNameSuffixHash: true
