{
 "title": "Speedtest Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Ping and Jitter (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum without (instance) (speedtest_ping_latency_milliseconds)",
     "legendFormat": "Ping (ms)"
    },
    {
     "expr": "sum without (instance) (speedtest_jitter_latency_milliseconds)",
     "legendFormat": "Jitter (ms)"
    }
   ]
  },
  {
   "title": "Download Speed (Mbits/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum without (instance) (speedtest_download_bits_per_second)  ",
     "legendFormat": "Download Speed"
    }
   ]
  },
  {
   "title": "Upload Speed (Mbits/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum without (instance) (speedtest_upload_bits_per_second)",
     "legendFormat": "Upload Speed"
    }
   ]
  }
 ]
}