apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  PRIVATE_DNS_PRIMARY: ENC[AES256_GCM,data:0AlorQh1Q6e2JAni,iv:+hVaxBRActfbBU6XiCwme9c2+sdJqVQ5p2BvDghqePI=,tag:u6hf25dZqHuV9bXmNtOW2A==,type:str]
  PRIVATE_GATEWAY: ENC[AES256_GCM,data:Y3UJBN7fl4bXQGlx,iv:lklwevrmIkZDX28+nvh5fZnQ+0kQAn/qPOgAsNmyHiM=,tag:GZ/B1gBpbFEjZdBrQ7yzGw==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:VSTdXcRHcq3uNjag7WRo7fPZCMc4Gl80ZqJG5XwVOTWazL5q,iv:6noRRybuItoA1FL/DXAgoNXH1HhN5XKlZa2EeP1ydAo=,tag:QU0hu2d8XkpWv6YIKICLvA==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:x6DnowNyaeMVYABY,iv:6q6ITxqZzQVvlcGHBm2KoFSO84J1rhJ6mNqNtYgj05o=,tag:UYlDGN6foWohZH7tF9ib+g==,type:str]
  #ENC[AES256_GCM,data:nw9+oN2/slT+7Vk7JA==,iv:uWMUBCdftLM7/JzoGY90Ts4PdIG6522iPvmnfcpLKf8=,tag:NX+n9kaTfLkziHoNEMdARQ==,type:comment]
  BACKUP_SERVER: ENC[AES256_GCM,data:Trgx/QuHwlfNFVPpBnemNL+oPnkNpA==,iv:PNo38uBTW2zQi2+KnfPKeorFf0LOb8QDu3J1dFd802U=,tag:DgBb/xoxXzDyUAb0ltpC7A==,type:str]
  BLACKBOX_EXPORTER_WIFI: ENC[AES256_GCM,data:A+W4KSvyE7wKwUjL0S0b9Q==,iv:imYyw6SjZnDmINNqmBDipVzPWXbI7J4KAoEpN2RdV2w=,tag:woa/JVJTDo8DQxP4lR5yMg==,type:str]
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:X9VzXU28HqChu5AX,iv:rirJ1JNdxruw2CApi697wGZNHr1KekQEwOH/SGAn+GM=,tag:EztMqIyAMSHcixnlHPtu/A==,type:str]
  HOMELAN_IPV4: ENC[AES256_GCM,data:ttj/Ex6HEsRARQPLBV+1,iv:7HHg5pu8q2yliDz9yh82mrZGWWaVl1V+gcJleBXMKC0=,tag:IVfRf2rbLMRZYJyBqw7hqw==,type:str]
  HOMELAN_IPV6: ENC[AES256_GCM,data:81FjGwdmsbeJ7OiRIKz8y7bsYw24,iv:Qvk9cIo7BXEfdTmO/Xvx+hXsORlo/h7hUMavDJpANHo=,tag:O9ZEQiqYMF/Hr4kmDlQkiA==,type:str]
  MEDIA_SERVER: ENC[AES256_GCM,data:3B06Wf1/g+apTnXgN89KzY48,iv:E3OGCnFn2kGXPQuJNn/Rc6thcrbB3iRMNkR6bZEp860=,tag:P4x7ZGVjZhqhWQEq3Xe5Tg==,type:str]
  NETWORK_STATUS_TARGET: ENC[AES256_GCM,data:tOBrAy6CKzdQ4WFRRbA+MQ==,iv:kBdXahSja7hL5TgRu0idMDce5lYxx7nENS+KbcsFkQU=,tag:RnbcN31cExLCYc4WrNQAFQ==,type:str]
  OPENWEATHERMAP_API_KEY: ENC[AES256_GCM,data:GoSwtYBV2J3+PoJ0C0KCnxF6Zt5mImfjVc1bDZ6ORGU=,iv:/WrDSzWNEXxpwLPgnKxtQrF/58KZuBY3Od/t6KlUU6k=,tag:Rilt2DjsN3USX0PCjOq32w==,type:str]
  PRIVATE_STATIC_DOMAIN: ENC[AES256_GCM,data:7aCTwcRbBRvAiHWy,iv:rWzKf8CRCnU7JCso33ChcshXeddPKiUIzW6eYw2ITgs=,tag:fBOOhzXIhEdlIc/qXw3UfA==,type:str]
  SMTP_SMARTHOST: ENC[AES256_GCM,data:dmWskokiWgPFEEupZg==,iv:6N82Q4aeCVCI0ZkKzEAGJBgY9Ya0a8PvSN+4KhCeyGs=,tag:NwMf4t9mEW0r3+DiQ2d1SA==,type:str]
  SMTP_SMARTHOST_PORT: ENC[AES256_GCM,data:DPP5F5o=,iv:IVkIFK91TiDF3uC93r8QPUM014EJWkO2cSnzFoLTgiM=,tag:pGWoLMn+VvgVwv/Y0hMnTQ==,type:str]
sops:
  age:
    - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbHhhVTczdnAwZkpRTWU3
        Sy9LQW56Tk9La0FVNU5STFZqRGJyUnNUVlVJCkt1L2hqWlhzd0c0MGd0UCtka0ZR
        WTl1QUswTDBkWkNuN3lJcmh0YXo1R2sKLS0tIFZlYXN3TUR1RURGaDFqZ2MzL2Z0
        b3hjcTh4QzlZa1diMkk2eTdta2lSb3cKbksrNVG16lBimvvDRGG4aDFYnCk4mTM0
        W+OdGUIHXbTf1Uejt7rdmv3rTmfiL3vzd6hfV+Q3Cd0HP7GM+Bm1ww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T15:54:04Z"
  mac: ENC[AES256_GCM,data:nURwTWeyOityI27eUezZFmSRus4vkgSqc6n/rAoNgfCyTDc/44152TZHUS52qDku8839M5+2MuzDGxdwpep8tVpnAyIZbDoFH3ZMjxYsW+QHNAQc+XIgZtgujBniJwDF/wnp+7vYmCCPK/6tFEUGAz3rdIndOivEC1AzTG+tAME=,iv:yzDJtPPthBHNjWmBkocRZIJ/JtvGJ7xQcZk5Zb6brgg=,tag:Z4CJkfO/mEfYHH4yZyy0Qg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
