---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-status-app
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-status-app-secret
    template:
      data:
        githubAppID: "{{ .BOT_CLIENT_ID }}"
        githubAppInstallationID: "{{ .BOT_APP_INSTALLATION_ID }}"
        githubAppPrivateKey: "{{ .BOT_APP_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: github-bot
