{
 "title": "Node Exporter Aggregate",
 "tags": [ "node-exporter-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_cpu:rate:sum / on (instance) instance:node_num_cpu:sum",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "5m Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load5{job=\"node-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (node_memory_MemFree_bytes{job=\"node-exporter\"} / node_memory_MemTotal_bytes{job=\"node-exporter\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Aggregated)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\n(\n  sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"})\n/\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\"})\n)\n"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"node-exporter\", device=~\"mmcblk.p2+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval])",
     "legendFormat": "{{ instance}} {{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"node-exporter\", device=~\"mmcblk.p2+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{device}} written"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"node-exporter\", device=~\"mmcblk.p2+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval])",
     "legendFormat": "{{ instance}} {{device}} io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "\n (\n    node_filesystem_size_bytes{job=\"node-exporter\",  fstype!=\"\", device=~\"/dev/(mmcblk0p2|vda1)\"}\n  -\n    node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", device=~\"/dev/(mmcblk0p2|vda1)\"}\n  )\n  / node_filesystem_size_bytes{job=\"node-exporter\",  fstype!=\"\", device=~\"/dev/(mmcblk0p2|vda1)\"}\n\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", device=~\"(en|eth).*\"}[$__rate_interval])",
     "legendFormat": "{{ instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", device=~\"(en|eth).*\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  }
 ]
}