---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-vault-plugin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: argocd-vault-plugin-credentials
    template:
      data:
        AVP_TYPE: 1passwordconnect
        OP_CONNECT_TOKEN: "{{ .OP_CONNECT_TOKEN }}"
        OP_CONNECT_HOST: http://onepassword-connect.security:80
  dataFrom:
    - extract:
        key: argocd
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: argocd-oidc-secret
    template:
      data:
        argocd_oidc_config: |
          name: Authelia
          issuer: https://auth.${CLUSTER_DOMAIN}
          clientID: argocd
          clientSecret: {{ .argocd_oauth_client_secret }}
          cliClientID: argocd
          requestedScopes: ["openid", "profile", "email", "groups"]
          requestedIDTokenClaims: {"groups": {"essential": true}}
  dataFrom:
    - extract:
        key: argocd
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9 -]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "argocd_$1"
