---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dmarc-report
spec:
  chartRef:
    kind: OCIRepository
    name: dmarc-report
  interval: 1h
  values:
    controllers:
      dmarc-report:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/haraldkoch/postgres-init
              tag: 18.6@sha256:3f1d734b05f605ef06a1a9ccda9c358658381f4cc825919e400521f943f9931b
            envFrom: &envFrom
              - secretRef:
                  name: *app
        containers:
          app:
            image:
              repository: ghcr.io/haraldkoch/dmarc-report
              tag: 1.4.5@sha256:9717142bb879e5622362419fd411aa27b83fcf49ce20908e9e5763a93d9bb3c1
            env:
              TZ: ${TIMEZONE:=Etc/UTC}
              REPORT_DB_TYPE: pgsql
            envFrom: *envFrom
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      app:
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        type: emptyDir
