---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radar
spec:
  components:
    - ../../../../components/gatus/guarded
  interval: 1h
  path: ./kubernetes/apps/base/radar/radar
  postBuild:
    substitute:
      APP: radar
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: radar
  wait: false
