---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: network-ups-tools
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: network-ups-tools-secret
    template:
      data:
        upsd.users: |
          [upsmon]
            password  = "{{ .network_ups_tools_upsmon_password }}"
            actions = SET
            instcmds = ALL
            upsmon primary
          [homeassistant]
            password = "{{ .network_ups_tools_homeassistant_password }}"
            actions = SET
            instcmds = ALL
        upsmon.conf: |
          MONITOR kubernetes@localhost:3493 1 upsmon "{{ .network_ups_tools_upsmon_password }}" primary
          SHUTDOWNCMD "/sbin/shutdown -h +0"
          POWERDOWNFLAG /etc/killpower
          POLLFREQ 15
          POLLFREQALERT 5
          HOSTSYNC 15
  dataFrom:
    - extract:
        key: network-ups-tools
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9 -]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "network_ups_tools_$1"
