---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: siren
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      siren:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/shamubernetes/siren
              tag: 1.4.29@sha256:716443d8bb798732ccf2c53ca74e92dc424d6d8a825b9495d7cba34c7a647cc7
            env:
              TZ: ${TIMEZONE}
              ALERTMANAGER_BASE_URL: http://alertmanager-operated.observability.svc.cluster.local:9093
              PORT: &port 3000
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /livez
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  timeoutSeconds: 5
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      tmpfs:
        type: emptyDir
        advancedMounts:
          siren:
            app:
              - path: /tmp
                subPath: tmp
