{
 "title": "Kasa",
 "description": "Visualize TP-Link Smart Plug metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(kasa_online)" }
   ]
  },
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(kasa_online==1)" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 13, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "kasa_relay_state", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Device with Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(kasa_relay_state==1)" }
   ]
  },
  {
   "title": "Total Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(kasa_power_load)" }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "kasa_power_load", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Energy Usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "increase(kasa_power_total[24h])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "kasa_voltage", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "kasa_current", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "kasa_rssi", "legendFormat": "{{alias}}" }
   ]
  }
 ]
}