apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:eGqELNIKQYT+g4wtpt+EGPCBxrAQ5eT5j5sJg1WYW2iFy0xG,iv:HTqJn2OFLk5hEHEXbijvFE683nqBm4AECg0+rPqaYew=,tag:T2X8+vxR32SUEjF5MjZmig==,type:str]
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:MWr8FcK5Z1ZduSZ0,iv:LG4YNwwD7vBJLFBLksv4sdCrX0E6jsmw3ftgdMMqJeE=,tag:fiDS7h5Oan2iCooSCqKpEw==,type:str]
  NETWORK_VPN_GATEWAY: ENC[AES256_GCM,data:GUDtaZjPn8kECu0=,iv:lGfrQb6G0JiQ7ksn5wkcYrmBguxj5WSI8QRPxo48f3g=,tag:BV4Q7OtJU1BNvLu0njIxxQ==,type:str]
  PRIVATE_STATIC_DOMAIN: ENC[AES256_GCM,data:x4kzaOh6KGZDFBD4,iv:4AP/VneXLDXOY++RaWzGTrpMn8REcv1LB3Xzz7FRi6c=,tag:oEbfqeTs17huRYta/28z7w==,type:str]
  SECRET_ONEDRIVE_AUTHRESPONSE: ENC[AES256_GCM,data:SW+KhAC8wGC5IspzPu8THtZzXWt2Z55KXWBYnhVGEY1BtijxcSsQCMNrFbgOzSo3zgeTAQR+wW84nMF/VA/2UQ7I3PzhnPcK5UXWjBUSE0gw0Ibbo64l+gi6Fj8jDsAfCYowsKlmTZmG/hlHmleBuyE9JLKl,iv:fRutXiyVeDTaj7UdwevLAbXepCPAGw11R/lqzCHwWM4=,tag:pfKooqbFxVHeo/kP7RW/Tg==,type:str]
  SECRET_WEB_BACKUP_USER: ENC[AES256_GCM,data:5ItM5A==,iv:ICIHYSQiHS6kfZbBVdEyuRrc5xkIVGapkcjPlm5YcqU=,tag:mzIIcyG8AYKyY6FEDu0niQ==,type:str]
  SECRET_WEB_HOST: ENC[AES256_GCM,data:22bQfVXh37geDIGD0EWnMacEqyk=,iv:7ufVPba9k0fHm6Tb+Od2sJzxylMgMCazOY1nFGi5UEw=,tag:18QQEokQeIDtYBWkD5pO7Q==,type:str]
sops:
  age:
    - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSWl4MWpXQXdodVRhWkk1
        b1VBUkFaeDVxM1BXbTBVOWdSdkdLQ0QyNlZZCmNzNXFaSTFwMU9jMDBNeVpHUTJ0
        cGovOFRqZlVmL0ZXU0JOWTY3WGJyZ1UKLS0tIGZOWHc1ZnFFMzFpbkt2SXlrZEov
        KzVTRzFlWlVyeWlXUmZQenMvaStvem8KFBbN3MDuMCzMZuuu+uGxHZLcyX8n4N3J
        +tTx4OQoZA27qIaxmtpzwnbcJEdXFNoZ8H5fDoXmbFk5TE9tZZ2nAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-19T17:59:41Z"
  mac: ENC[AES256_GCM,data:t0EC/wKFvjI2fTTDVkz0gOlOniGN5jEl2K2n9rPf+V+Astsbhn5pseptuf51s9TWpwJ+7wOMUmP9v1/Lr8RtWluvCtxDUzpATZtiXOAKMH08zkS72rrgTMFRTU4mxPTh00XyDkzl+RO7hkcM30JTK3LLHS5zQLL+4eptxrz/8B0=,iv:1IN+uROTdilTepbGZu1LaNQTwBPOiDzdjANI7GcbnoY=,tag:ttCWo4qxR8sxfQp4sF+egA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
