apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:lAaJxWyQBbhZl9w14NEFLH0dRioKpZFiB9lLYIiKgWblb8ka,iv:1WxkYrY8HR16hLT+pBLZwF+NBVpIQD+MArr5uCtOYV0=,tag:QEAm2Q0YTMjnJm29ptiJyA==,type:str]
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:wAPsOWWT0fSLLFC+,iv:oNq3I3U+qUoxefUTPTbdQXhrboLqi9+7Xh26Zi9WWiA=,tag:xJDwMOzQQDN87LJwvpUI6w==,type:str]
  HASS_NUT_PASSWORD: ENC[AES256_GCM,data:Dtpo/n5ipkuC4v/0COxt8BepiXc=,iv:1KNnp0mi22rWvulTBgwwsSv2CkI3bwQbyDwT+rM+f0o=,tag:Z+lr4qjcOFZfBf4iN99VKQ==,type:str]
  NETWORK_VPN_GATEWAY: ENC[AES256_GCM,data:sNRFFZwlMZbJG64=,iv:Y1jXV7ze5midTzPji9+A6ZMLdpDezfbbrysQpjztNOA=,tag:A6hqu6f/xRbQ5UOeTmGbXw==,type:str]
  NUT_PASSWORD: ENC[AES256_GCM,data:ReAx0Iivq0cSBUnz/FUtlocnBhM=,iv:7XD8MFlkMQfr3GaRoJiP/MP3JqhS+bBeFRdT71pMTqo=,tag:wbyWN5a5+IH/hLiHeyNhYA==,type:str]
  PRIVATE_STATIC_DOMAIN: ENC[AES256_GCM,data:QvZ2N/0iujfFWltp,iv:VMlVdarCYrQZ6HL66FZYbDAnJOrwTxXyYexawtRPEgE=,tag:GhbbcdMOs2Bv36eos1HNoQ==,type:str]
  SECRET_ONEDRIVE_AUTHRESPONSE: ENC[AES256_GCM,data:DrDvZwOSc3LKoFqABSG589+rjMWr7Jcp5vAP6XKpJpxN0AR6sLBlg19yQzc5cVDu8gYMbtLDnMrKUWH/WRE1riqzpszDGmOz3na7jeIdTt7b/wgw5xF2qRsQ13NRuU+21jPPG+7V7KnsNVH2FeS0QRvcp2ls,iv:KSFMPaD1F6X7mFyRvuUupwOIYfdMwisoOVyCtOIFVnA=,tag:aI10wASMWT5IEinrDbcgNg==,type:str]
  SECRET_WEB_BACKUP_USER: ENC[AES256_GCM,data:wk1KnA==,iv:JWJG3vnuBaVQ0b+QkBFULR4mLgaULC4K9E1I9Mhiax4=,tag:4LU/REZMA0E2Zonkaigklw==,type:str]
  SECRET_WEB_HOST: ENC[AES256_GCM,data:Sh2kHJ5yxvcErDEWjVznaTsmtCs=,iv:NaMRb4BCXl2K3vdiR+MP5Rq5yi27gTgoni/+lOhnC00=,tag:CECXyAyU7laRjcB/DB7SeA==,type:str]
sops:
  age:
    - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMG0yQnV6eUlieUp6eWtl
        UTR6bXNSS1JKbW9ELzJpUzB4dU9mVDk1dmtnCjl2TDlrbjlsaStHcTBqYTQrekhI
        cjhERXRhRU0vYkg5THVmb3RwMlI5YlUKLS0tIFlFbmoxVldydFp0Vmx4U3lMSzg3
        OWVYdkR5V2hNUVBYRDZLeW1KV0ZTajgK3I9lWmB5M7x4NZg9EkCDjwPGeLDLRjhr
        P5fFZoIl9bsxbzlI14sPFHL1BjNV0x5nUVNXyPu6BheeR2IjOqYTGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-19T17:44:19Z"
  mac: ENC[AES256_GCM,data:LDr2Qnsn6/ECInDPKPV3HKdk3LOERxSmzC8a/viQDuNuM2b1GBQXoMITmME9utWxCyx1v50+wgWtXgtVxuyfa6V8IofbGxYmz/YoSAgIMBProssaFIZXQVDnohi1KKrAfBwusXXA6mhKFb4Rj6bkk7up4Xd6OgYHH2tg/kxbq9c=,iv:SS9G7mZpFL+sokxWXkO8f2hMpNM9AqGCp8V4XCs6utg=,tag:mGNh/jJMI9xrCa4p/eeTHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
