apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:khY7HLXEDdwZvwQKBLPGbctuDN7O5NXaoVnUR/VNv3wj0AY+,iv:Mb/ForxYmKFgOhF8cE6aJsqjDMB5kzROHObCrS9h2JU=,tag:+JPPjr6EkI2m8lXyMMlOGw==,type:str]
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:/q+aPb2SZHxMedxS,iv:8xQjF48qbMPYEdW1fe2/aiiYzgC3IJa9bRRXoHnd1qQ=,tag:20XCjZu8uSvsbEA8gsgDTA==,type:str]
  NETWORK_VPN_GATEWAY: ENC[AES256_GCM,data:0WOvl2XMqjTsUxQ=,iv:eYassdIzKtdpW64d7GS8/Pm1zArnXZOR1VjYUwBIZwc=,tag:6Szlk3JY4m5j5XDh2B6QIw==,type:str]
  PRIVATE_STATIC_DOMAIN: ENC[AES256_GCM,data:fxFRCGAHGBSESFXk,iv:x7IekX+9whGN7brTGh3eSLnpdCLeSuowm30fRBDOijY=,tag:Cd/cADJsSAhhpixkstqwHQ==,type:str]
  SECRET_WEB_BACKUP_USER: ENC[AES256_GCM,data:kwb9yA==,iv:oGqyl4wDnBDqZiP0bteIIxUFXTjJoh0rJmTup1oidNs=,tag:7126d5kh8m2mgbczPGCW0A==,type:str]
  SECRET_WEB_HOST: ENC[AES256_GCM,data:COU/0+epyi/I3pa9CyQfS9QEmlc=,iv:ZrLcgEeCU+hFl3n1NMLAajnb8Gndm/hF6zfUObYKiSs=,tag:P+/n077UBiN40XmN3j7v1g==,type:str]
sops:
  age:
    - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTXlubmtScGNvQU1sdXFJ
        SGNxamM2OVI0Qk1uNVVUc2Q4aVBuYlJGVUFRClpLR2tJWnZzRTAxdkowUTdzR0FV
        MmlWcGNMeGwzZXJNd0V6a2RoVGlTSzAKLS0tIFRMc2pDYVpPYlRFR21kdE8xN3hW
        aWNBbWpLYitSWnUzQ0FkbCtGZU1iNmsKe39jP9BL4+f/hV/PuT9MwhfyT2rINIET
        XdBcpMNUmUb49R/1vtCI4ZX6XgnS82cefhS8rXgYMu1YyfT2ufX4ow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-19T18:07:11Z"
  mac: ENC[AES256_GCM,data:kc2uCoVqS5uMcoNTMVkiXe8aAoFxB2WU5yOc3GiuAj4LPqBw91lcDMub7xKyXc2jNjVQS6kCdAF1t6U8nYsGi1FMCu/SGGDpu3jSF2t3WK9wGkZRDvi0gp9Xe2XOV315wXnElbujTDalw64/A0Yk4iTgmRDMr/LMLoKhJsGlTvM=,iv:RmhEWe5XFrKhx4kow0IfyFbNyMTykUhHgkFoEGJ/B20=,tag:T4watNkNy/7jowJFhxVcrQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
