---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mindwtr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mindwtr-secret
    template:
      data:
        MINDWTR_CLOUD_AUTH_TOKENS: "{{ .mindwtr_cloud_auth_tokens }}"
  dataFrom:
    - extract:
        key: mindwtr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mindwtr_$1"
