---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name kopiur-ui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kopiur-ui-proxy-token
    template:
      data:
        token: "{{ .kopiur_ui_proxy_token }}"
  dataFrom:
    - extract:
        key: kopiur
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9-]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "kopiur_$1"
