---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopiur
spec:
  chartRef:
    kind: OCIRepository
    name: kopiur
  interval: 1h
  values:
    features:
      credentialProjection:
        enabled: true
    installScope: cluster
    monitoring:
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          matchLabels:
            dashboards: grafana
          folder: infrastructure
      prometheusRule:
        enabled: true
      serviceMonitor:
        enabled: false
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1022
      runAsGroup: 1022
      fsGroup: 1022
      fsGroupChangePolicy: OnRootMismatch
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
    ui:
      enabled: true
      auth:
        userHeader: Remote-User
        groupsHeader: Remote-Groups
        groupsSeparator: ","
        emailHeader: Remote-Email
        # this token must appear in the X-Kopiur-Proxy-Token header
        proxySecret:
          existingSecret: kopiur-ui-proxy-token
          key: token
      rbac:
        userRoles: true
      networkPolicy:
        enabled: true
        proxySelector:
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: network
          podSelector:
            matchLabels:
              gateway.networking.k8s.io/gateway-name: envoy-internal
        monitoringSelector:
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
