---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tududi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tududi-secret
    template:
      data:
        # App
        TUDUDI_SESSION_SECRET: "{{ .tududi_session_secret }}"
        DATABASE_URL: "postgres://{{ .tududi_postgres_user }}:{{ .tududi_postgres_pass }}@postgres-rw.dbms/tududi?sslmode=disable"
        OIDC_CLIENT_ID: "{{ .tududi_oidc_client_id }}"
        OIDC_CLIENT_SECRET: "{{ .tududi_oidc_client_secret }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: tududi
        INIT_POSTGRES_HOST: postgres-rw.dbms.svc.cluster.local.
        INIT_POSTGRES_USER: "{{ .tududi_postgres_user }}"
        INIT_POSTGRES_PASS: "{{ .tududi_postgres_pass }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: tududi
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9 -]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "tududi_$1"
    - extract:
        key: cloudnative-pg
