---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openweathermap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openweathermap-secret
    template:
      data:
        openweathermap_api_key: "{{ .openweathermap_api_key }}"
  dataFrom:
    - extract:
        key: openweathermap
      rewrite:
        - regexp:
            source: "(.*)"
            target: "openweathermap_$1"
    - extract:
        key: openweathermap
