---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blackbox-exporter
spec:
  components:
    - ../../../../components/gatus/guarded
  interval: 1h
  path: ./kubernetes/apps/base/observability/blackbox-exporter
  postBuild:
    substitute:
      APP: blackbox-exporter
      GATUS_SUBDOMAIN: blackbox
      SUBDOMAIN: blackbox
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
