apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:VSTdXcRHcq3uNjag7WRo7fPZCMc4Gl80ZqJG5XwVOTWazL5q,iv:6noRRybuItoA1FL/DXAgoNXH1HhN5XKlZa2EeP1ydAo=,tag:QU0hu2d8XkpWv6YIKICLvA==,type:str]
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:X9VzXU28HqChu5AX,iv:rirJ1JNdxruw2CApi697wGZNHr1KekQEwOH/SGAn+GM=,tag:EztMqIyAMSHcixnlHPtu/A==,type:str]
  OPENWEATHERMAP_API_KEY: ENC[AES256_GCM,data:GoSwtYBV2J3+PoJ0C0KCnxF6Zt5mImfjVc1bDZ6ORGU=,iv:/WrDSzWNEXxpwLPgnKxtQrF/58KZuBY3Od/t6KlUU6k=,tag:Rilt2DjsN3USX0PCjOq32w==,type:str]
  PRIVATE_STATIC_DOMAIN: ENC[AES256_GCM,data:7aCTwcRbBRvAiHWy,iv:rWzKf8CRCnU7JCso33ChcshXeddPKiUIzW6eYw2ITgs=,tag:fBOOhzXIhEdlIc/qXw3UfA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbHhhVTczdnAwZkpRTWU3
        Sy9LQW56Tk9La0FVNU5STFZqRGJyUnNUVlVJCkt1L2hqWlhzd0c0MGd0UCtka0ZR
        WTl1QUswTDBkWkNuN3lJcmh0YXo1R2sKLS0tIFZlYXN3TUR1RURGaDFqZ2MzL2Z0
        b3hjcTh4QzlZa1diMkk2eTdta2lSb3cKbksrNVG16lBimvvDRGG4aDFYnCk4mTM0
        W+OdGUIHXbTf1Uejt7rdmv3rTmfiL3vzd6hfV+Q3Cd0HP7GM+Bm1ww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T21:05:17Z"
  mac: ENC[AES256_GCM,data:XpVHOg8YNOOZsNl+2aJZz4r3+Dj8cKp0b7d16uCUzOUW9RDgufBL2QiIHEYQDGkbb68riYxyA77FQW/UQ++hnNlDoFEJ2SQKBF4fU7IgCQdZGRv453YyfypdiYqvRrGf18MMoDTGT1IfZyROol2LxhRyWA3jX8rY36RYMQZabw0=,iv:YGbh8wmuNNLopo9SM63U6bJStBF5ELiZs3aEEB5kcSE=,tag:TZhullAluwHjidQC7HGr2Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
