---
title: Dashboard
favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
theme: dark
color: slate
headerStyle: clean
statusStyle: dot
useEqualHeights: false
fiveColumns: true
quickLaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
layout:
  Calendar:
    style: column
    icon: mdi-calendar
    initiallyCollapsed: false
  Media:
    style: column
    icon: mdi-play-circle
  Infrastructure:
    style: column
    icon: mdi-server
  Storage:
    style: column
    icon: mdi-desktop-tower
  Home:
    style: column
    icon: mdi-home-analytics
  Observability:
    style: column
    icon: mdi-chart-line
  Downloads:
    style: column
    icon: mdi-download-circle
