---
apiVersion: batch/v1
kind: Job
metadata:
  name: tekton-results-db-job
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - envFrom:
          - secretRef:
              name: tekton-results-postgres
        image: ghcr.io/haraldkoch/postgres-init:18.4@sha256:3fef5a5bcfe4c26efa7ffb6302936e1b18644bfb0b7de2007cf5871b9a7a5b7e
        name: init-db
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: OnFailure
