---
apiVersion: batch/v1
kind: Job
metadata:
  name: tekton-results-db-job
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - envFrom:
          - secretRef:
              name: tekton-results-postgres
        image: ghcr.io/haraldkoch/postgres-init:18.4@sha256:2afd59dcc153c6ff909a20bb0f76a97dae8973c0d4061b96087254bb30a5fcce
        name: init-db
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: OnFailure
