---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
spec:
  components:
    - ../../../../components/gatus/guarded
  dependsOn:
    - name: longhorn
      namespace: storage
  interval: 1h
  path: ./kubernetes/apps/base/observability/kube-prometheus-stack
  postBuild:
    substitute:
      ALERTMANAGER_PEER: amcluster-main
      ALERTMANAGER_SUBDOMAIN: alertmanager
      APP: kube-prometheus-stack
      GATUS_SUBDOMAIN: prometheus
      PROMETHEUS_SUBDOMAIN: prometheus
      PVC_CAPACITY: "50"
      STORAGECLASS: longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
