---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/monitoring.coreos.com/probe_v1.json
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: ping-wifi
spec:
  module: icmp_wifi
  metricRelabelings:
    - action: labeldrop
      regex: (pod)
  prober:
    url: 192.168.10.2:9115
  targets:
    staticConfig:
      static:
        - captive.apple.com
