---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zipline
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: zipline-secret
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .aws_secret_access_key }}"
        CORE_SECRET: "{{ .core_secret }}"
        OIDC_CLIENT_ID: "{{ .oidc_client_id }}"
        OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        DATABASE_URL: "postgres://{{ .postgres_user }}:{{ .postgres_pass }}@postgres-rw.dbms/zipline?sslmode=disable"
        # Postgres Init
        INIT_POSTGRES_DBNAME: zipline
        INIT_POSTGRES_HOST: postgres-rw.dbms.svc.cluster.local.
        INIT_POSTGRES_USER: "{{ .postgres_user }}"
        INIT_POSTGRES_PASS: "{{ .postgres_pass }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: zipline
    - extract:
        key: cloudnative-pg
