---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zipline
spec:
  chartRef:
    kind: OCIRepository
    name: zipline
  interval: 1h
  values:
    controllers:
      zipline:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/haraldkoch/postgres-init
              tag: 18.6@sha256:3f1d734b05f605ef06a1a9ccda9c358658381f4cc825919e400521f943f9931b
            envFrom:
              - secretRef:
                  name: zipline-secret
        containers:
          zipline:
            image:
              repository: ghcr.io/diced/zipline
              tag: 4.8.0@sha256:8ae3cdf8cdbba2ac98754e9fc4ccec67bbaa86b6e6ab1ccf9683ddcff85eee72
            env:
              CORE_DEFAULT_DOMAIN: zipline.${CLUSTER_DOMAIN}
              CORE_HOSTNAME: 0.0.0.0
              CORE_PORT: &port 3000
              CORE_RETURN_HTTPS_URLS: "true"
              CORE_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: zipline-secret
                    key: CORE_SECRET
              CORE_TEMP_DIRECTORY: /tmp/zipline
              CORE_TRUST_PROXY: "true"
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: zipline-secret
                    key: DATABASE_URL
              DATASOURCE_S3_ACCESS_KEY_ID:
                valueFrom:
                  secretKeyRef:
                    name: zipline-secret
                    key: AWS_ACCESS_KEY_ID
              DATASOURCE_S3_BUCKET: zipline
              DATASOURCE_S3_ENDPOINT: http://mnemosyne.home.arpa:3900
              DATASOURCE_S3_FORCE_PATH_STYLE: "true"
              DATASOURCE_S3_REGION: garage
              DATASOURCE_S3_SECRET_ACCESS_KEY:
                valueFrom:
                  secretKeyRef:
                    name: zipline-secret
                    key: AWS_SECRET_ACCESS_KEY
              DATASOURCE_TYPE: s3
              FEATURES_HEALTHCHECK: "true"
              FEATURES_METRICS_ENABLED: "true"
              FEATURES_OAUTH_REGISTRATION: "true"
              FEATURES_THUMBNAILS_ENABLED: "true"
              FEATURES_THUMBNAILS_FORMAT: "webp"
              FEATURES_USER_REGISTRATION: "false"
              FEATURES_VERSION_CHECKING: "false"
              OAUTH_BYPASS_LOCAL_LOGIN: "true"
              OAUTH_OIDC_AUTHORIZE_URL: https://auth.${CLUSTER_DOMAIN}/api/oidc/authorization
              OAUTH_OIDC_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: zipline-secret
                    key: OIDC_CLIENT_ID
              OAUTH_OIDC_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: zipline-secret
                    key: OIDC_CLIENT_SECRET
              OAUTH_OIDC_REDIRECT_URI: https://zipline.${CLUSTER_DOMAIN}/api/auth/oauth/oidc
              OAUTH_OIDC_TOKEN_URL: https://auth.${CLUSTER_DOMAIN}/api/oidc/token
              OAUTH_OIDC_USERINFO_URL: https://auth.${CLUSTER_DOMAIN}/api/oidc/userinfo
              TZ: America/Toronto
              ZIPLINE_NO_COLOR: "true"
            envFrom:
              - secretRef:
                  name: zipline-secret
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/healthcheck
                    port: *port
              readiness: *probe
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    route:
      zipline:
        hostnames:
          - zipline.${CLUSTER_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - port: *port
                name: zipline
    service:
      zipline:
        controller: zipline
        ports:
          http:
            port: *port
