{
 "title": "Omada Controller",
 "description": "Dashboard for omada-controller",
 "tags": [ "omada-controller" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": "label_values(omada_device_uptime_seconds, site)"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(omada_device_uptime_seconds{site=\"$Site\"}, device)"
   }
  ]
 },
 "panels": [
  { "title": "Omada Controller", "type": "row", "gridPos": { "x": 0, "y": 0, "w": 24, "h": 1 } },
  {
   "title": "Total PoE Used",
   "type": "stat",
   "gridPos": { "x": 0, "y": 1, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(omada_port_power_watts{site=~\"$site\"})"
    }
   ]
  },
  {
   "title": "Controller Uptime",
   "type": "stat",
   "gridPos": { "x": 6, "y": 1, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "omada_controller_uptime_seconds{site=~\"$site\"}"
    }
   ]
  },
  {
   "title": "Active Switch Ports",
   "type": "stat",
   "gridPos": { "x": 12, "y": 1, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(omada_port_link_status{site=~\"$site\"})"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "x": 18, "y": 1, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(omada_client_connected_total{site=~\"$site\"})"
    }
   ]
  },
  { "title": "Omada Devices", "type": "row", "gridPos": { "x": 0, "y": 5, "w": 24, "h": 1 } },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(omada_device_cpu_percentage{site=~\"$site\"}) by (ip, device, device_type, mac, model, site)",
     "legendFormat": "{{ device }} {{ device_type }} {{ ip }}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(omada_device_mem_percentage{site=~\"$site\"}) by (ip, device, device_type, mac, model, site)",
     "legendFormat": "{{ device }} {{ device_type }} {{ ip }}"
    }
   ]
  },
  {
   "title": "Rx/Tx Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 8, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(omada_device_rx_rate{site=~\"$site\"}) by (ip, device, device_type, mac, model, site)",
     "legendFormat": "Rx - {{ device }} {{ device_type }} {{ ip }}"
    },
    {
     "expr": "-sum(omada_device_tx_rate{site=~\"$site\"}) by (ip, device, device_type, mac, model, site)",
     "legendFormat": "Tx - {{ device }} {{ device_type }} {{ ip }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 16, "w": 8, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(omada_device_uptime_seconds{site=~\"$site\"}) by (ip, device, device_type, mac, model, site)",
     "legendFormat": "{{ device }} {{ device_type }} {{ ip }}"
    }
   ]
  },
  {
   "title": "PoE remaining",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 16, "w": 8, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(omada_device_poe_remain_watts{site=~\"$site\"}) by (ip, device, device_type, mac, model, site)",
     "legendFormat": "{{ device }} {{ device_type }} {{ ip }}"
    }
   ]
  },
  { "title": "Omada Clients", "type": "row", "gridPos": { "x": 0, "y": 26, "w": 24, "h": 1 } },
  {
   "title": "Clients Connected",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 27, "w": 12, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(omada_client_connected_total{site=~\"$site\"}) by (connection_mode, wifi_mode)",
     "legendFormat": "{{ connection_mode }} {{ wifi_mode }}"
    }
   ]
  },
  {
   "title": "Signal Percentage",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 27, "w": 12, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(omada_client_signal_pct{site=~\"$site\", ip!=\"\"}) by (client, ap_name, connection_mode, ip, ssid, vlan_id, wifi_mode)",
     "legendFormat": "{{ client }} {{ ap_name }} {{ connection_mode }} {{ ssid }} {{ vlan_id }} {{ wifi_mode }}"
    }
   ]
  },
  {
   "title": "RSSI dBm",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 37, "w": 12, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sum(omada_client_rssi_dbm{site=~\"$site\", ip!=\"\"}) by (client, ap_name, connection_mode, ip, ssid, vlan_id, wifi_mode)",
     "legendFormat": "{{ client }} {{ ap_name }} {{ connection_mode }} {{ ssid }} {{ vlan_id }} {{ wifi_mode }}"
    }
   ]
  },
  {
   "title": "SNR dBm",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 37, "w": 12, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sum(omada_client_snr_dbm{site=~\"$site\", ip!=\"\"}) by (client, ap_name, connection_mode, ip, ssid, vlan_id, wifi_mode)",
     "legendFormat": "{{ client }} {{ ap_name }} {{ connection_mode }} {{ ssid }} {{ vlan_id }} {{ wifi_mode }}"
    }
   ]
  },
  {
   "title": "Upload Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 47, "w": 12, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(omada_client_traffic_up_bytes{site=~\"$site\", ip!=\"\"}[$__rate_interval])) by (client, ap_name, connection_mode, ip, ssid, vlan_id, wifi_mode)",
     "legendFormat": "{{ client }} {{ ap_name }} {{ connection_mode }} {{ ssid }} {{ vlan_id }} {{ wifi_mode }}"
    }
   ]
  },
  {
   "title": "Download Rate",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 47, "w": 12, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(omada_client_traffic_down_bytes{site=~\"$site\", ip!=\"\"}[$__rate_interval])) by (client, ap_name, connection_mode, ip, ssid, vlan_id, wifi_mode)",
     "legendFormat": "{{ client }} {{ ap_name }} {{ connection_mode }} {{ ssid }} {{ vlan_id }} {{ wifi_mode }}"
    }
   ]
  },
  {
   "title": "Rx Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 57, "w": 12, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(omada_client_rx_rate{site=~\"$site\", ip!=\"\"}) by (client, ap_name, connection_mode, ip, ssid, vlan_id, wifi_mode)",
     "legendFormat": "{{ client }} {{ ap_name }} {{ connection_mode }} {{ ssid }} {{ vlan_id }} {{ wifi_mode }}"
    }
   ]
  },
  {
   "title": "Tx Rate",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 57, "w": 12, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(omada_client_tx_rate{site=~\"$site\", ip!=\"\"}) by (client, ap_name, connection_mode, ip, ssid, vlan_id, wifi_mode)",
     "legendFormat": "{{ client }} {{ ap_name }} {{ connection_mode }} {{ ssid }} {{ vlan_id }} {{ wifi_mode }}"
    }
   ]
  },
  { "title": "Omada Ports", "type": "row", "gridPos": { "x": 0, "y": 67, "w": 24, "h": 1 } },
  {
   "title": "Port Link Status",
   "type": "table",
   "gridPos": { "x": 0, "y": 68, "w": 24, "h": 24 },
   "targets": [
    {
     "expr": "sum(omada_port_link_status{site=~\"$site\"}) by (client, device, name, profile, site, switch_port, vlan_id)"
    },
    {
     "expr": "sum(increase(omada_port_link_rx{site=~\"$site\"}[$__range])) by (switch_port)"
    },
    {
     "expr": "sum(increase(omada_port_link_tx{site=~\"$site\"}[$__range])) by (switch_port)"
    },
    {
     "expr": "sum(omada_port_link_speed_mbps{site=~\"$site\"}) by (client, device, name, profile, site, switch_port, vlan_id)"
    },
    {
     "expr": "sum(omada_port_power_watts{site=~\"$site\"}) by (client, device, name, profile, site, switch_port, vlan_id)"
    }
   ]
  }
 ]
}