---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name kochhaus-home-runner-${CLUSTER}
spec:
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
  interval: 1h
  values:
    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes:
          - ReadWriteOnce
        storageClassName: openebs-hostpath
        resources:
          requests:
            storage: 25Gi
    controllerServiceAccount:
      name: actions-runner-controller
      namespace: actions-runner-system
    githubConfigSecret: kochhaus-home-runner-secret
    githubConfigUrl: https://github.com/haraldkoch/kochhaus-home
    maxRunners: ${maxRunners:=2} # Double total nodes
    minRunners: ${minRunners:=1}
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/haraldkoch/actions-runner:2.335.1@sha256:7893bbddcaf599ca211076991e9ad98fbe12719c620cecfea5e1adb61cff0ab1
            command:
              - /home/runner/run.sh
            env:
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"
              - name: NODE
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
            volumeMounts:
              - mountPath: /var/run/secrets/talos.dev
                name: talos
                readOnly: true
        serviceAccountName: *name
        volumes:
          - name: talos
            secret:
              secretName: *name
