---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: trek-secret
    template:
      data:
        ENCRYPTION_KEY: "{{ .trek_encryption_key }}"
        OIDC_CLIENT_ID: trek
        OIDC_CLIENT_SECRET: "{{ .trek_oidc_client_secret }}"
  dataFrom:
    - extract:
        key: trek
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9 -]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "trek_$1"
