---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencloud
spec:
  chartRef:
    kind: OCIRepository
    name: opencloud
  interval: 1h
  values:
    controllers:
      opencloud:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mirror.gcr.io/opencloudeu/opencloud-rolling
              tag: 6.1.0@sha256:235b5d988729aa821bd068bbdc60175270b05bd5fefa77b6d0e2ec5aeadccd0b
            command:
              - /bin/sh
              - -c
              - opencloud init || true; opencloud server
            env:
              NOTIFICATIONS_SMTP_HOST: smtp.${CLUSTER_DOMAIN}
              NOTIFICATIONS_SMTP_INSECURE: false
              NOTIFICATIONS_SMTP_PORT: "25"
              NOTIFICATIONS_SMTP_SENDER: OpenCloud Admin <opencloud@${CLUSTER_DOMAIN}>
              OC_INSECURE: true
              OC_LOG_LEVEL: info
              PROXY_TLS: false
              OC_URL: https://{{ .Release.Name }}.${CLUSTER_DOMAIN}
              # we use external LDAP server so we don't have to deal with certificate maintenance chore
              OC_ADMIN_USER_ID: "b8b2089b-f34c-38ba-9e08-4f0871fc6efb"
              OC_EXCLUDE_RUN_SERVICES: idm
              OC_LDAP_BIND_DN: cn=opencloud_bind,ou=people,dc=home,dc=arpa
              OC_LDAP_INSECURE: true
              OC_LDAP_DISABLE_USER_MECHANISM: none
              OC_LDAP_GROUP_BASE_DN: ou=groups,dc=home,dc=arpa
              OC_LDAP_GROUP_SCHEMA_ID: entryuuid
              OC_LDAP_SERVER_WRITE_ENABLED: true
              OC_LDAP_URI: ldap://lldap.security.svc.cluster.local:389
              OC_LDAP_USER_BASE_DN: ou=people,dc=home,dc=arpa
              OC_LDAP_USER_SCHEMA_ID: entryuuid
              OC_LDAP_USER_FILTER: (objectClass=person)
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 9200
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 5
              readiness: *probes
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "${SUBDOMAIN}.${CLUSTER_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: "${VOLSYNC_CLAIM}"
        globalMounts:
          - path: /etc/opencloud
            subPath: config
          - path: /var/lib/opencloud
            subPath: data
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
