---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Namespace
      name: not-used
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: not-used
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/warn: baseline
          pod-security.kubernetes.io/audit: baseline
