---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network

components:
  - ../../components/common

resources:
  - ./namespace.yaml
  - ./certificates.yaml
  - ./bind-dns.yaml
  - ./cloudflare-dns.yaml
  - ./cloudflare-tunnel.yaml
  - ./dyndns/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./multus/ks.yaml
