---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  KUBE_API_IPV4: 192.168.23.65
  HARBOR_INT_IPV4: 192.168.23.81
  GATEWAY_INT_IPV4: 192.168.23.80
  GATEWAY_EXT_IPV4: 192.168.23.90