apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:XwlTN5Ow7zg2qEGQ,iv:6lStd4kWLC7w0lSDlm778pgoJ508N2gBE6oxL+yR+Yw=,tag:rIBjwW9NG6xgH7sy/n91Rg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:PyUvel5YhsRCmKOvIbLW2fHGiXsNinh8ZYDQks7nO7bmQyRG,iv:fsqviCKYvfSSCT/hV2Vtzprv7ecm33B3O8Q+VWShwWY=,tag:DBxOOFj7WjLVaAzYirIY2Q==,type:str]
    SECRET_BACKUP_SERVER: ENC[AES256_GCM,data:uAOXdVusLpE7GCLTQnPIKnhgI6h3rQ==,iv:IuMDNmyuRWQuxZ/fPgNluE8AEepTrv9rDUJsMwG3vYM=,tag:OX//dj5rzBLH66NmwSUQOQ==,type:str]
    SECRET_DNS_PRIMARY: ENC[AES256_GCM,data:PH849DNtEvs2aXCD,iv:rcRAfeEMvu1KD4Z5WbMzyyMr+66F5D/sPeysVsj2CzM=,tag:qo7z4AcU2PWUHNcxNk9gMw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:uusm333Ct3C7Kbbo,iv:cEwZWmtB2tEl4lARHVypzDT5khvflF9lWHGw3zm9frA=,tag:X/Zezfv1Dg89E+oV2ed9lg==,type:str]
    SECRET_HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:5bS/k61MaUHHKp+3s2hYbg==,iv:43fHdPplFtM9bfAwdNdgXql4/BennvQjCqX0Um53zZU=,tag:CRi1ay6xHhl9VI3yKan2MQ==,type:str]
    SECRET_HARBOR_ENCRPYTION_KEY: ENC[AES256_GCM,data:JKBfsSP4xgk7Il940YyPew==,iv:kPftFvXOEB0uFz8yfm2qFjAS3NIzzBEIOK5+mfjLEiU=,tag:UyCwjmJ+fHv/LHNKy5iWvQ==,type:str]
    SECRET_HARBOR_POSTGRES_PASSWORD: ENC[AES256_GCM,data:CnyqatK8L4hbJ9RY/ttmqqCuZ59G1/Q8DUUCuQ==,iv:ixp1YsAVn5P15LWbxuur1QDB9I/ktKJdUFuJxTBV6g0=,tag:bbV9Ub+RbDGZyBsWoz4zvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWFFwUDZXQjlkc2w5a2hJ
            WG9OYVZiemd1TkErQjZBem1Yb0pHVHNac0hrCmRTdkRianEwSWFpc1M1eXdOSTda
            bkRjaWRFN0VVbHRoQm1heVVSVWlBNWsKLS0tIEFkUmRER1UvM2tEQ1lISkI4bjda
            UHJRQnNHb1FTWjVmaERWQkl2ZkJBZHMKGiKAL4m0kr0NGNwb7A2UnzAJbepd4+sm
            Fc7u40byTyqfg8WbNCzUoC/6QKUISeVFVSBw3udcp+J1C6u9dvdkpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T22:00:52Z"
    mac: ENC[AES256_GCM,data:NjoxIOcPbHzZFZu0qy6LzSegpTZxtl0M+Innv7YH9gZUi5XtLb8eI8XXZPSFXy3TSvCqEmYo9BIDBYQhZuoJNgWhYlLfgBPIgYDvTWAXWANgYD6gGsXp6JzS88dhBo/FZvx/4/xWQ/+Ru6IZvKNOfNVxDQJa0eIPGA114i5TYo4=,iv:lnTf1vg/u8/1+Ewqwhlu9glwNhnYb9r8ddKwYbcwmtU=,tag:WfGy5KNBEX1gnu9MJyHsaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
