apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:SswGIAlYKqFQ/eRg,iv:LYU2KwhAkM7oXFhwD1teTAZtB+L6Zh9Cvb7NW2jNxJs=,tag:ICH7r08d+qEVD1ExgUQpAQ==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:6BXIJDbohHN7l8xOJyRILm5eKSvf31sDsxySZ2PkCALlvY5V,iv:RrLlZe6Jv81mcN61KjMKkMbC+hhpmodhBVF81yAt9ug=,tag:iX4lLYfeIhk29Mm3OH1QXA==,type:str]
  SECRET_BACKUP_SERVER: ENC[AES256_GCM,data:I59FB7xF0kJPl/0syzV0gdFhEc80Cg==,iv:Tze3JSR2yMG1FemIVbKmkuraiH7wlubNqVSHRKUFBtw=,tag:uwOby+J7RPnvVLsJVxuCWA==,type:str]
  SECRET_DNS_PRIMARY: ENC[AES256_GCM,data:GpViKzj/bFPi6qAh,iv:ZDmAvTbeOabp+ZOvgqY7b8REuDXbq5YKdEqzzASqySk=,tag:3tjwtM7BLKnFME0sYeDcKA==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:D0f/7zy3ZhDvfW75,iv:1RCY4gDSdrFbEym5Saph3pj8AHVVyODpaWKeAxLdlTw=,tag:m2muZuTBhvEi8/dL9KlF/A==,type:str]
  SECRET_HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:K/PF6+fhwCaXiaRKCxWP/w==,iv:jhjQ1mqUGptCHxtoYzsecu0fKLSpWizDt/cAs3YAWYE=,tag:2xWxPR/sHPiTscWC879cZA==,type:str]
  SECRET_HARBOR_ENCRPYTION_KEY: ENC[AES256_GCM,data:iLFAjhsMVCJmyYY5TWbpyg==,iv:YY3pH7DJVKa1sD7uf27Crg+M0gFOyOMUW7f7cSdlfJs=,tag:P5pbNzCUStpXnwdJ+TliSQ==,type:str]
  SECRET_HARBOR_POSTGRES_PASSWORD: ENC[AES256_GCM,data:AInVffFEIJAjKyxlHKYOS3jEpbTodlAazh0gbg==,iv:tYTWBNToOLnx1mPYIZ9YBHT1bkU0bC9AFGNVS7gOC24=,tag:JXM3aP4qQ0aIEatv7QTbuA==,type:str]
sops:
  age:
    - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaHk5VW1OQjdjRDV5SDR5
        cTR0UEc2Tlk0bkZJcVh6VEhSOUR0Q3VJS1ZFCi92WkVtUFVXSWx4MWdUeE4yQXp3
        VDkyRUZ0ZkNlOWF6OHBGUWJSeHBsdWMKLS0tIHAwbGtzQWJkK2gyOWhrTm8wVmIy
        cFhSV085ZitkSWdGbVVuaE8ydWU3ZUUKYLuzgS6zKIBooZd/ogsw3TNar1opa+8B
        N7V6kMuuwDkASd5hoHGS4tHoPblUQo9p9swIB4JBH0pI9VAsFuzbXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T15:54:50Z"
  mac: ENC[AES256_GCM,data:bw5QdNg5v+6pNYnN6m3l46TMv+tMcjVZceO3Z30L9UTggXbtzwxbz+4QEB32STtLnP7eM0FtwYjIwYL1tS2FemTP+LAhIQGGmEVlLO/GM1uEEC7vd0TyFG2IM7Wgwqts5CMGxWmxWGz8/o0V2NfFyGhwhoBSWilREo4Df476FA4=,iv:SbuOvgqXSIj2LQsOeafkfH2UCUpwgsf+xf6P01CnZRA=,tag:5NCCniiu0CL7SRNIlyO/2A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
