apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:4XrtyOTnqEZrBOmO,iv:mACZrMPTS+m5z2nhyHt40ZQkqvgnNo8U5dap8IVnuX0=,tag:RqgYCQVX/HptGYtV+AoZUw==,type:str]
  SECRET_BACKUP_SERVER: ENC[AES256_GCM,data:pGMJVCgB5BbrkX8IH116xahwrdJFKw==,iv:X5LOPhCOu9BPQJ0Qb0xPVDegSRyta7I6mTwnehkpJig=,tag:UXUfo+/MJ/jkMpS2ZRzfEg==,type:str]
  SECRET_DNS_PRIMARY: ENC[AES256_GCM,data:ej+ABS+IgaRCQHrD,iv:I8GMpwN0fTzuQ9jWxHZsIncqTwQQhL0Efyk0nA1pew8=,tag:+8YrwCs4viy2AdbSOgIEbw==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:UQivkmQZ+Md/ynhw,iv:6PEsW0IYqf6BD8pqn/jUrNE3Cb2l7hdLLKBmFw4GG2w=,tag:TEDhJxoDxbHfF+juYN6FWg==,type:str]
  SECRET_HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:nkPXi8LpmOnY0C77Q5irRQ==,iv:EYuj+iz7rxWYnYcpMXJgwp+ABRumYSgq79Qh1TC1FZ8=,tag:kc00FSTx5t6QMc8YR0yabQ==,type:str]
  SECRET_HARBOR_ENCRPYTION_KEY: ENC[AES256_GCM,data:98wK7VgkTJoBYZLsljdipw==,iv:9P8u2N+3TsYsR5ngdgl/DNuDNzEJQY5ivHI2s1NYZqc=,tag:9+xFfbD5tUfiWFLPVk83Ug==,type:str]
  SECRET_HARBOR_POSTGRES_PASSWORD: ENC[AES256_GCM,data:1rGhVl3Zf0qcVv1Yg94R+DP3ArAIUvd5GtOkqQ==,iv:kOWfBBGkX1x8yoSpbi7pLiT97PIt3EUf3B5nPS0xTwc=,tag:PCDQF/bTTmMSYZeQVOAs+w==,type:str]
sops:
  age:
    - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZ0pWelk4dHFwU1ZtdTZF
        ZkhZalAwajR3MXRBV2xJLzJuSWd3MlpoOVV3CnM2ZVVUQmZFNUc4c2RZeEtlRElo
        UVBNVzQ0dXhsQ250V20yaEVFS1BWL2cKLS0tIHZTcml0Vyt3cDc1aTY3RExEdi9n
        dE9WbUREdGJBMEcyRGRXVXlxc2hmNDAKPXza1DwiJrS1OV7i1gk/rYhYp4t8cLp/
        Soa5aZ9enpG6ZCfxS+sUfmAIHPaXkeEVWAYxRYY1yNc6k3O1Skf1+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T21:36:41Z"
  mac: ENC[AES256_GCM,data:8k4rHAEkoicFvr0NVaOu8B7tI78/FtI92BYgjD6ACpFLjIRAKNDhIYwCnCW0azh717oiKoemmBI/v7GuIjRwmYq7Z5p0tPhTX3Wgck5XEyxR4RVvdZdnY2e2+eRXs3z0bWwVmtGKpCJeglnJD7cxA4bYEn47Kv3Uc92R0ROgtGI=,iv:sAm14pLWuZBj4R632ZvnHkJ3pYJPrZX2yhH6jhr6438=,tag:hvrm1tZDo7NfisE6wYCh9Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
