---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app excalidraw
spec:
  chartRef:
    kind: OCIRepository
    name: excalidraw
  interval: 1h
  values:
    controllers:
      excalidraw:
        replicas: 2
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: mirror.gcr.io/excalidraw/excalidraw
              tag: latest@sha256:b6cd04431d88f2756a7c3095cf7970884e8fd6b2800c9445b5a60a5c715bbf0c
              pullPolicy: IfNotPresent
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 5m
                memory: 10Mi
              limits:
                memory: 50Mi
    defaultPodOptions:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
    service:
      app:
        ipFamilyPolicy: PreferDualStack
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - "draw.${CLUSTER_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
