---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.14/website/content/v1.14/schemas/config.schema.json
apiVersion: v1alpha1
kind: UnattendedInstallConfig
provisioning:
  diskSelector:
    match: disk.model == "Samsung SSD 860"
---
apiVersion: v1alpha1
kind: KubeNodeConfig
taints:
  node-role.kubernetes.io/control-plane: :NoSchedule
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: k3sm
---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
links:
  - net0
bondMode: active-backup
miimon: 100
mtu: 1500
addresses:
  - address: 192.168.20.18/24
  - address: fdd5:aa8:9535:20::18/64
routes:
  - gateway: 192.168.20.1
  - gateway: fdd5:aa8:9535:20::1
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: net0
selector:
  match: link.driver == "e1000e" && mac(link.permanent_addr) == "c8:d3:ff:a5:8a:c8"
