---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

components:
  - ../../components/common

replacements:
  - path: ../../../components/replacements/ks.yaml

resources:
  - ./namespace.yaml
  - ./blackbox-exporter.yaml
  - ./gatus/ks.yaml
  - ./goldpinger/ks.yaml
  - ./grafana/ks.yaml
  - ./karma.yaml
  - ./keda.yaml
  - ./kromgo/ks.yaml
  - ./kube-prometheus-stack.yaml
  - ./network-ups-tools/ks.yaml
  - ./silence-operator/ks.yaml
  - ./siren.yaml
  - ./smartctl-exporter.yaml
  - ./smokeping/ks.yaml
  - ./speedtest-exporter/ks.yaml
  - ./tplink-plug-exporter.yaml
  - ./victoria-logs/ks.yaml
  - ./victoria-logs.yaml
