---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Namespace
      name: _
    patch: |-
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1warn
        value: baseline
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1audit
        value: baseline
