---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pocket-id-secret
    template:
      data:
        ENCRYPTION_KEY: "{{ .pocket_id_encryption_key }}"
        LDAP_BIND_DN: "{{ .pocket_id_ldap_bind_dn }}"
        LDAP_BIND_PASSWORD: "{{ .pocket_id_ldap_bind_password }}"
        MAXMIND_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
  dataFrom:
    - extract:
        key: maxmind
        property: MAXMIND_LICENSE_KEY
    - extract:
        key: pocket-id
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9 -]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "pocket_id_$1"
