---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: syncthing
spec:
  components:
    - ../../../../components/keda/nfs-scaler
  dependsOn:
    - name: keda
      namespace: observability
  interval: 1h
  path: ./kubernetes/apps/base/default/syncthing
  postBuild:
    substitute:
      APP: syncthing
      SYNCTHING_IPV4: 192.168.21.103
      SYNCTHING_IPV6: fdd5:aa8:9535:21::103
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
