apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    labels:
        reconcile.fluxcd.io/watch: Enabled
stringData:
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:k4blfJpMn0D7mKYRNvdimUPolfF+KRoNOVhxiVOjbWNNU4J8,iv:xhCfZfEc2AtzT4YzmsiAV9BwLQ1cw0JHezG0AjcD2oI=,tag:C2/iBYIhDEqIu/g6o8CIKA==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:UV6feEM4HhZ12Zd1,iv:9ixoxGd/d9mtwYa67vE0mWD+9vdgS7U1GcgV2HOUZn0=,tag:pDjFzkI69ARtap7KL8TOBw==,type:str]
    PRIVATE_STATIC_DOMAIN: ENC[AES256_GCM,data:miGbYNLRVDObcvln,iv:U5g6b7VkTrnzP90ph0ijsrPrEcXvC3wX7TgMGT7Vf8I=,tag:mRljpQlF3tXCnl1/7Lh1Vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUFRrNmxtekhaM1lFWFZL
            L0drVDlQa2NHcTNxQmR5REZsbytzd1UwOGhRCnRwL3ZXTFNXWHZXdHNTTklPMEtj
            bDdmbUgxcUk1NFU4N3lQSWFFdTl6VzQKLS0tIExDcXlHMkE2YnBxTXRZZUhHUVVt
            RDNIUFJGbXdlWEFKV3ZWTmtKY1JiWXMKdxxREXHt82aK3VvlYh9EHO9ZrURdV1cH
            MPKoIfmTL7/ybSGkTIEoDTA9Wj7BshGlEQhk0lN6PtrWZ0q8okrsHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T20:12:14Z"
    mac: ENC[AES256_GCM,data:Zj6ubgrJdoTzFarJ2xG5lV9Yq+5vK0NC0a5PEeiOW9A8u3r5gxlDHfaGlO0fgmoOAUs4bslqCzVl4DI82v8SS8wzBeKLWcgkYIGJi2rMrFPRXzVOChjyG5satuxhpSRuVjhRl6oNF15pMathfDWmd3Nq4jzaOiaKKdkfakqsRi0=,iv:zkyvqNgu6gYR4La7i+bm21VXWkjnEVwBw6VbQwPLeOk=,tag:XBVrolGCGHnV3W8NFeezJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
