---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/common

replacements:
  - path: ../../../components/replacements/ks.yaml

resources:
  - ./namespace.yaml
  - ./bentopdf.yaml
  - ./blocky-ui.yaml
  - ./changedetection.yaml
  - ./echo.yaml
  - ./esphome.yaml
  - ./hassproxy.yaml
  - ./homer.yaml
  - ./it-tools.yaml
  - ./kochhaus-docs.yaml
  - ./matter-server.yaml
  - ./matterbridge.yaml
  - ./mosquitto.yaml
  - ./mqtt-exporter.yaml
  - ./netshoot-iot.yaml
  - ./node-red.yaml
  - ./omada-controller-proxy.yaml
  - ./openspeedtest.yaml
  - ./openweathermap-exporter.yaml
  - ./populator-test/ks.yaml
  - ./smtp-relay.yaml
  - ./zigbee2mqtt.yaml
