apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    labels:
        reconcile.fluxcd.io/watch: Enabled
stringData:
    BACKUP_SERVER: ENC[AES256_GCM,data:90sted0g2vDjNEt2KOtIfDqBhd7g+w==,iv:2NTmdpPWZG4ti6rbSHV0QZFGl2CAmg5hXbS/NRFVHHE=,tag:aoEjC+p2ixoIUo0vdeQ+iQ==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:pfJp9vGeKHFf5BNm,iv:QLEiSolqAD7G/OtVCpzH8txJKKZIsX+xxMLCvJU/oIY=,tag:aikjjWutek05A/he2OkBLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZ0hCZGpEK2dObCtQdGEw
            WlBDeVVaOUJPTm9MY1FWdWZ3Nk4rSGJFdkg4CmNXajh4OTUveFJyZ0JqbEZ5T1dG
            cjN1YTZwUDFOcE1SUExkbDVOYlBRS0kKLS0tIGp3S2lqUy9VUFk3WnVNWE95Y1JM
            dWNEcnlpb0t3b3NaajdETVp5Um1aa2cKmjGhF9XF7GI9agIEgBD7trEM46jbxo+f
            oEJUdrhykX5vHjBy86DJAul1cQq9lT3S/tSXz4hU4/9rdfQ/nzPzHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T20:16:34Z"
    mac: ENC[AES256_GCM,data:WQxlc4AdMM2rnVZ6+gYyWsNKqjxgj3j7a1WNXAXlJ+jW9H6Orq8tJm72wIRWgaSydFaPtbIoujW89WPSmOVH7yqsCJRTaowp1A6QR5UCmbVImpauNvs9VWy/gzohcjvzhQ8JGMnW1XscklJcRhzG/XbddN+c4mOMoxJybNAvMR4=,iv:S1L31AJfQ5SlsQZEpGtmtcW0AFRVmR5YAE8VI+eHN10=,tag:sz6UXyZhvWyOPXdUaNZ4Rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
