apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
stringData:
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:pfJp9vGeKHFf5BNm,iv:QLEiSolqAD7G/OtVCpzH8txJKKZIsX+xxMLCvJU/oIY=,tag:aikjjWutek05A/he2OkBLQ==,type:str]
  PRIVATE_STATIC_DOMAIN: ENC[AES256_GCM,data:OfDYeSiG3zlwi2ez,iv:B4dI50GNUv6yBYFz0ZuruVtFppPu5g06G7Jl0d6M3ZY=,tag:bZ8YyZ0jmh5+qsXRw9Yv7Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZ0hCZGpEK2dObCtQdGEw
        WlBDeVVaOUJPTm9MY1FWdWZ3Nk4rSGJFdkg4CmNXajh4OTUveFJyZ0JqbEZ5T1dG
        cjN1YTZwUDFOcE1SUExkbDVOYlBRS0kKLS0tIGp3S2lqUy9VUFk3WnVNWE95Y1JM
        dWNEcnlpb0t3b3NaajdETVp5Um1aa2cKmjGhF9XF7GI9agIEgBD7trEM46jbxo+f
        oEJUdrhykX5vHjBy86DJAul1cQq9lT3S/tSXz4hU4/9rdfQ/nzPzHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T18:38:12Z"
  mac: ENC[AES256_GCM,data:NSH08CGMrzMtpi9sVIYTWC4Jtp/sekiFb0XwzybYP/ws44E6MrlkkJp97/MQmTlFCUoylYkDTV4xu3PSuLKynImsDVgn5gOagFZD50v8qUSdSAVVmcmpeapU+7F32uBJLX5j04Trum8K+Wam2vPCxbtuyo1uXBoxtugKmkb/v9I=,iv:BhpexITZedUY6WIai+WXaqZ+aHg1vYcmOEukRyoTC7Y=,tag:JxEZQYBn6RYfBBAIy98eyQ==,type:str]
  version: 3.13.3
