{
 "title": "House Sensors",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "All Temperatures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mqtt_temperature", "legendFormat": "{{topic}}" }
   ]
  },
  {
   "title": "House Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "mqtt_temperature{topic=~\".*(Upstairs|Office|Thermostat|Downstairs).*\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Garage Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "mqtt_temperature{topic=\"zigbee2mqtt_Garage Sensor\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "House Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mqtt_humidity{topic=~\".*(Upstairs|Office|Thermostat|Downstairs).*\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Garage Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mqtt_humidity{topic=\"zigbee2mqtt_Garage Sensor\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Barometric Pressure (corrected to STP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "mqtt_pressure * (1-(0.0065*154)/ on() group_left () (openweathermap_temperature_celsius + 0.0065*154 + 273.15))^-5.257",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Battery Levels",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mqtt_battery", "legendFormat": "{{topic}}" }
   ]
  }
 ]
}