---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
spec:
  chartRef:
    kind: OCIRepository
    name: gatus
  interval: 1h
  values:
    controllers:
      gatus:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/haraldkoch/postgres-init
              tag: 18.4@sha256:632c31c178240a811496586553f5ae9baa08e26841da7dd59aaa086ae5284316
            envFrom: &envFrom
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
          init-config:
            dependsOn: init-db
            image:
              repository: ghcr.io/home-operations/k8s-sidecar
              tag: 2.7.3@sha256:391ccddbc6b29b1b07fea530950eba68e941304ea9252084e07cf12f1687a81d
            env:
              FOLDER: /config
              LABEL: gatus.io/enabled
              NAMESPACE: ALL
              RESOURCE: both
              UNIQUE_FILENAMES: true
              METHOD: WATCH
            resources:
              requests:
                cpu: 10m
                memory: 240Mi
              limits:
                memory: 320Mi
            restartPolicy: Always
        containers:
          app:
            image:
              repository: ghcr.io/twin/gatus
              tag: v5.36.0@sha256:c5f210d095fa78e6efaa20ffeb14803f2ba4f10615e16a6d12087697149617f0
            env:
              GATUS_CONFIG_PATH: /config
              GATUS_DELAY_START_SECONDS: 5
              GATUS_WEB_PORT: &port 80
              TZ: ${TIMEZONE:=Etc/UTC}
            envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 128Mi
    defaultPodOptions:
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        sysctls:
          - name: net.ipv4.ping_group_range
            value: "0 2147483647"
    service:
      app:
        ipFamilyPolicy: PreferDualStack
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        endpoints:
          - port: http
            metricRelabelings:
              - action: labeldrop
                regex: (pod)
              - action: replace
                sourceLabels:
                  - "service"
                targetLabel: instance
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
          - status.${CLUSTER_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
    rbac:
      roles:
        gatus:
          type: ClusterRole
          rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
                - secrets
              verbs:
                - get
                - watch
                - list
      bindings:
        gatus:
          type: ClusterRoleBinding
          roleRef:
            identifier: gatus
          subjects:
            - identifier: gatus
    persistence:
      config:
        type: emptyDir
      config-file:
        type: configMap
        name: "{{ .Release.Name }}-configmap"
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
