---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onedrive
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: onedrive-secret
    template:
      data:
        ONEDRIVE_AUTHRESPONSE: "{{ .onedrive_authresponse }}"
  dataFrom:
    - extract:
        key: onedrive
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9 -]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "onedrive_$1"
