{
 "title": "Network Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Internet Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8*(irate(ifHCInOctets{job='snmp-exporter-opnsense',instance='192.168.20.1',ifDescr=~'igc3|pppoe0'}[$__rate_interval]) or irate(ifInOctets{job='snmp-exporter-opnsense',instance='192.168.20.1',ifDescr=~'igc3|pppoe0'}[$__rate_interval]))",
     "legendFormat": "DOWN"
    },
    {
     "expr": "-8*(irate(ifHCOutOctets{job='snmp-exporter-opnsense',instance='192.168.20.1',ifDescr=~'igc3|pppoe0'}[$__rate_interval]) or irate(ifOutOctets{job='snmp-exporter-opnsense',instance='199.168.20.1',ifDescr=~'igc3|pppoe0'}[$__rate_interval]))",
     "legendFormat": "UP"
    }
   ]
  },
  {
   "title": "PING (Wired)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(probe_icmp_duration_seconds{instance=\"phaedra.cfrq.net\",phase=\"rtt\",job=~'.*ping-wired-4'}[$__interval])",
     "legendFormat": "{{job}} RTT"
    },
    {
     "expr": "1-avg_over_time(probe_success{instance=\"phaedra.cfrq.net\",job=~\".*ping-wired-4\"}[$__interval])",
     "legendFormat": "{{ job}} drops"
    }
   ]
  },
  {
   "title": "PING (Wi-Fi)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(probe_icmp_duration_seconds{instance=\"phaedra.cfrq.net\",phase=\"rtt\",job=~\".*ping-wifi*\"}[$__interval])",
     "legendFormat": "{{job}} RTT"
    },
    {
     "expr": "1-avg_over_time(probe_success{instance=\"phaedra.cfrq.net\",job=~\".*ping-wifi*\"}[$__interval])",
     "legendFormat": "{{ job}} drops"
    }
   ]
  },
  { "title": "LOCAL", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 } },
  {
   "title": "LAN UPS (gauge)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{instance=\"internet\"}"
    }
   ]
  },
  {
   "title": "LAN UPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{instance=\"internet\"}",
     "legendFormat": "charge"
    },
    {
     "expr": "network_ups_tools_battery_runtime{instance=\"internet\"}",
     "legendFormat": "runtime"
    }
   ]
  },
  { "title": "UTC", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 } }
 ]
}