---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mqtt-exporter
spec:
  interval: 1h
  path: ./kubernetes/apps/base/default/mqtt-exporter
  postBuild:
    substitute:
      SVC_MQTT_EXPORTER: 192.168.22.105,fdd5:aa8:9535:22::105
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
