---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.11/website/content/v1.11/schemas/config.schema.json
machine:
  install:
    diskSelector:
      model: P3-512
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: k3s3
---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
links:
  - net0
bondMode: active-backup
miimon: 100
mtu: 1500
addresses:
  - address: 192.168.20.24/24
  - address: fdd5:aa8:9535:20::24/64
routes:
  - gateway: 192.168.20.1
  - gateway: fdd5:aa8:9535:20::1
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: net0
selector:
  match: link.driver == "e1000e" && mac(link.permanent_addr) == "6c:4b:90:37:e2:a5"
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 200GB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: extra
provisioning:
  diskSelector:
    match: system_disk
  grow: true
  minSize: 200GB
  maxSize: 300GB
filesystem:
  type: xfs
