---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: blog
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: blog-secret
    template:
      data:
        repository: "{{ .repository }}"
        rsync_dest: "{{ .rsync_dest }}"
  dataFrom:
    - extract:
        key: weblog
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: blog-ssh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: blog-ssh-secret
  data:
    - secretKey: id_ed25519
      remoteRef:
        key: weblog
        property: id_ed25519
    - secretKey: ssh_config
      remoteRef:
        key: weblog
        property: ssh_config
    - secretKey: ssh_known_hosts
      remoteRef:
        key: weblog
        property: ssh_known_hosts
