apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Rpqy33cP4r9yep34Vb1sIoWiciREV60briQQBrAy96dHNcoo,iv:C8ue+wo/LLmhYyZkym+a47s6DVY/1RQ6tTb79MJbmB8=,tag:m91tBCeadEQEdnbfQg8IOQ==,type:str]
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:4QixVor2Ljc/Qf/i,iv:RiYaohRDgFuwnZCqYGL6D5O5GqmJFNCAYOeK+0GFZD8=,tag:WkHynZRoPecdrHv3oxKx8w==,type:str]
  NETWORK_VPN_GATEWAY: ENC[AES256_GCM,data:k5XP5nHE4UqNZO4=,iv:Uf6oFCy0okSfn0dA2Li7iu6keA3Wui7q97Bov3e3fLY=,tag:by7zdMrwkyd11DuWbmtDCQ==,type:str]
  PRIVATE_STATIC_DOMAIN: ENC[AES256_GCM,data:YgugLj0OUy0tlpHL,iv:XYzH+fj4gBq1OfcFQF6rK369LNKoQHGVDOLA2sWyZRE=,tag:TLNzgfiOiF+vkUQc0nercA==,type:str]
sops:
  age:
    - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UHZOTVI1UVhMdjVld0lP
        SjFiNGZKTEluOGsvOUN6YXpSQWtwdFVjTUVFCnlsS01zejJRM0Q4bkUrd0hsME94
        UE5mR2plcXZLVzNhYXZBWWVtQ1crUEEKLS0tIE1UaWxKRWlxU013dURvdEJqM1Bp
        OFpVVnB2QWRRVW1oMGlVK3BKRVZWL3MKHXV0B0wea0imoKHHrPNn82A6oRnscJIy
        3QBgqQgWIjzRFVCXVmLZJDcLEupH71M3OenMWpUoc8X4PMpUjd0Hig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-19T18:17:13Z"
  mac: ENC[AES256_GCM,data:+VIzxdNTEqCaG/hJ1yrPiw1Mhamz7r2RoB4kGSl5xDdVRgYsCLLkE5NsELy5DbDTaTa3CgUpWgQClg/x7XSSFPbtogGUUsaSnuky1ZyBs8GMv/YgVfEJB331IODt1/V0jtUslQTrk04nLgcv3qvG4epIOwURhpY1biXHHDe6KFw=,iv:BaJWXzQmNJKbJSKmt5rLFGHL1S5gRD0nrTiDtMnPjJU=,tag:6FI6OWGToFrH+1/hskNL3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
